<?php
/*
 * foot.inc
 *
 * Adapted from pfSense (https://www.pfsense.org)
 * Copyright (c) 2004-2013 BSD Perimeter
 * Copyright (c) 2013-2016 Electric Sheep Fencing
 * Copyright (c) 2014-2026 Rubicon Communications, LLC (Netgate)
 * Adapted for MitraNet Rinjani 1.0.2 Native Linux Appliance
 *
 * Licensed under the Apache License, Version 2.0.
 */
?>
	</div>
	<footer class="footer">
		<div class="container">
			<p class="text-muted">
				<a id="tpl" style="display: none;" href="#" title="Top of page"><i class="fa-regular fa-square-caret-up pull-left"></i></a>
				<small><strong>MitraNet Rinjani 1.0.2</strong> (Debian 13 Trixie amd64) &bull; Native Linux Network OS &bull; Adapted from pfSense &copy; 2004-2026 Electric Sheep Fencing, LLC / Netgate</small>
				<a id="tpr" style="display: none;" href="#" title="Top of page"><i class="fa-regular fa-square-caret-up pull-right"></i></a>
			</p>
		</div>
	</footer>

	<script src="/vendor/jquery/jquery-3.7.1.min.js"></script>
	<script src="/vendor/jquery-ui/jquery-ui-1.13.2.min.js"></script>
	<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="/js/pfSense.js"></script>
	<script src="/js/pfSenseHelpers.js"></script>
	<script src="/vendor/sortable/sortable.js"></script>

	<script type="text/javascript">
	//<![CDATA[
		if ($(document).height() > $(window).height()) {
		    $('[id^=tp]').show();
		}
	//]]>
	</script>
</body>
</html>
