#!/bin/sh
#
#
# bsdinstall pfSense installation module.
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2023i-2024 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BSDINSTALL_INC_PATH="/usr/libexec/bsdinstall"
. "${BSDINSTALL_INC_PATH}/pfSense-common"

hndi() {
	local _ndi="${1}"

	LEN="$(echo "${_ndi}" | "${AWK}" '{print length($0)}')"
	if [ "${LEN}" -ne "${NDI_SIZE}" ]; then
		echo -n "${_NDI}"
		return 0
	fi
	I=1
	unset ndi
	while [ "${I}" -lt "${NDI_SIZE}" ]; do
		N="$(echo "${NDI}" | "${AWK}" "{print substr(\$0, ${I}, 4)}")"
		if [ -n "${ndi}" ]; then
			ndi="${ndi} ${N}"
		else
			ndi="${N}"
		fi
		I=$(( ${I} + 4 ))
	done
	echo -n "${ndi}"
}

exit 0
