FreeBSD: { enabled: no }

pfSense-core: {
    url: "pkg+https://pkg.pfsense.org/pfSense_v2_9_0_amd64-core",
    mirror_type: "srv",
    signature_type: "fingerprints",
    fingerprints: "/usr/local/share/pfSense/keys/pkg",
    enabled: yes
}

pfSense: {
    url: "pkg+https://pkg.pfsense.org/pfSense_v2_9_0_amd64-pfSense_v2_9_0",
    mirror_type: "srv",
    signature_type: "fingerprints",
    fingerprints: "/usr/local/share/pfSense/keys/pkg",
    enabled: yes
}
