"""
MitraNet FilterLog Service.
Native Linux replacement for FreeBSD filterlog.
Parses nftables / netfilter kernel packet log messages into structured data.
"""

import re
import typing

class FilterLogService:
    """Parses and formats netfilter / nftables packet log records."""

    NFT_LOG_PATTERN = re.compile(
        r"(?P<prefix>[\w\-]+):\s+IN=(?P<in_if>\w*)\s+OUT=(?P<out_if>\w*)"
        r"(?:\s+MAC=(?P<mac>[0-9a-fA-F:]+))?"
        r"\s+SRC=(?P<src_ip>[0-9a-fA-F\.:]+)\s+DST=(?P<dst_ip>[0-9a-fA-F\.:]+)"
        r"(?:\s+LEN=(?P<length>\d+))?"
        r"(?:\s+PROTO=(?P<proto>\w+))?"
        r"(?:\s+SPT=(?P<src_port>\d+))?"
        r"(?:\s+DPT=(?P<dst_port>\d+))?"
    )

    @classmethod
    def parse_line(cls, line: str) -> typing.Optional[typing.Dict[str, typing.Any]]:
        """Parses a single kernel log line generated by nftables log rule."""
        match = cls.NFT_LOG_PATTERN.search(line)
        if not match:
            return None
        data = match.groupdict()
        return {
            "prefix": data.get("prefix") or "default",
            "in_interface": data.get("in_if") or None,
            "out_interface": data.get("out_if") or None,
            "src_ip": data.get("src_ip"),
            "dst_ip": data.get("dst_ip"),
            "length": int(data["length"]) if data.get("length") else None,
            "protocol": data.get("proto") or "UNKNOWN",
            "src_port": int(data["src_port"]) if data.get("src_port") else None,
            "dst_port": int(data["dst_port"]) if data.get("dst_port") else None,
        }
