"""
MitraNet nftables Firewall and NAT Rules Compiler.
Compiles high-level MitraNet configuration models into atomic nftables rule batches.
"""

from typing import List
from mitranet.src.config.models import (
    MitraNetMasterConfig,
    FirewallRule,
    PortForwardRule,
    OutboundNatRule,
    FirewallAlias,
)


class NftablesCompiler:
    """Translates MitraNet firewall and NAT declarative models into atomic nftables syntax."""

    @classmethod
    def compile_ruleset(cls, config: MitraNetMasterConfig) -> str:
        lines: List[str] = [
            "#!/usr/sbin/nft -f",
            "# Automatically generated by MitraNet Network OS",
            "# Atomic flush and rebuild of mitranet table",
            "flush ruleset",
            "",
            "table inet mitranet {",
        ]

        # 1. Compile Sets (Aliases)
        for alias in config.firewall_aliases:
            lines.extend(cls._compile_alias_set(alias))

        # 2. Compile Filter Chains
        lines.extend([
            "    chain input {",
            "        type filter hook input priority 0; policy drop;",
            "        # Conntrack established/related",
            "        ct state established,related accept",
            "        ct state invalid drop",
            "        # Localhost loopback traffic",
            "        iifname \"lo\" accept",
            "        # ICMP echo-request (ping)",
            "        ip protocol icmp icmp type echo-request accept",
            "        ip6 nexthdr icmpv6 icmpv6 type { echo-request, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept",
        ])

        for rule in config.firewall_rules:
            if rule.direction == "in" and rule.enabled:
                lines.append(f"        {cls._compile_rule(rule)}")

        lines.extend([
            "    }",
            "",
            "    chain forward {",
            "        type filter hook forward priority 0; policy drop;",
            "        ct state established,related accept",
            "        ct state invalid drop",
        ])

        for rule in config.firewall_rules:
            if rule.direction == "out" or rule.interface != "any":
                if rule.enabled:
                    lines.append(f"        {cls._compile_rule(rule)}")

        lines.extend([
            "    }",
            "",
            "    chain output {",
            "        type filter hook output priority 0; policy accept;",
            "    }",
            "",
        ])

        # 3. Compile NAT Chains
        lines.extend([
            "    chain prerouting_nat {",
            "        type nat hook prerouting priority dstnat; policy accept;",
        ])

        for pf in config.nat_port_forwards:
            if pf.enabled:
                lines.append(
                    f"        iifname \"{pf.interface}\" {pf.protocol} dport {pf.external_port} "
                    f"dnat to {pf.internal_ip}:{pf.internal_port} "
                    f"comment \"{pf.description or pf.id}\""
                )

        lines.extend([
            "    }",
            "",
            "    chain postrouting_nat {",
            "        type nat hook postrouting priority srcnat; policy accept;",
        ])

        for ob in config.nat_outbound:
            if ob.enabled:
                if ob.mode == "masquerade":
                    lines.append(
                        f"        oifname \"{ob.interface}\" ip saddr {ob.source} masquerade "
                        f"comment \"{ob.description or 'Outbound Masquerade'}\""
                    )
                elif ob.mode == "snat" and ob.target_ip:
                    lines.append(
                        f"        oifname \"{ob.interface}\" ip saddr {ob.source} snat to {ob.target_ip} "
                        f"comment \"{ob.description or 'Static SNAT'}\""
                    )

        lines.extend([
            "    }",
            "}",
            "",
        ])

        return "\n".join(lines)

    @classmethod
    def _compile_alias_set(cls, alias: FirewallAlias) -> List[str]:
        set_type = "ipv4_addr" if alias.type in ["host", "network"] else "inet_service"
        elements = ", ".join(alias.entries)
        return [
            f"    set {alias.name} {{",
            f"        type {set_type}",
            f"        elements = {{ {elements} }}",
            "    }",
        ]

    @classmethod
    def _compile_rule(cls, rule: FirewallRule) -> str:
        parts: List[str] = []

        if rule.interface != "any":
            parts.append(f"iifname \"{rule.interface}\"")

        if rule.protocol != "any":
            if rule.protocol == "tcp_udp":
                parts.append("meta l4proto { tcp, udp }")
            else:
                parts.append(f"{rule.protocol}")

        if rule.source != "any":
            if rule.source.startswith("@") or not ("." in rule.source or ":" in rule.source):
                # Named alias reference
                alias_ref = rule.source.lstrip("@")
                parts.append(f"ip saddr @{alias_ref}")
            else:
                parts.append(f"ip saddr {rule.source}")

        if rule.destination != "any":
            if rule.destination.startswith("@") or not ("." in rule.destination or ":" in rule.destination):
                alias_ref = rule.destination.lstrip("@")
                parts.append(f"ip daddr @{alias_ref}")
            else:
                parts.append(f"ip daddr {rule.destination}")

        if rule.destination_port:
            parts.append(f"dport {rule.destination_port}")

        if rule.log:
            parts.append("log prefix \"[MITRANET-FW] \"")

        verdict = rule.action
        parts.append(verdict)

        if rule.description:
            parts.append(f"comment \"{rule.description}\"")

        return " ".join(parts)
