<?php
/*
 * pkg_mgr.php - MitraNet Package Manager: Available Packages & Synchronization
 * Comprehensive 69+ Package Porting Matrix (.pkg -> .deb) from pfSense 2.9
 * Licensed under the Apache License, Version 2.0.
 */

$pgtitle = array("System", "Package Manager", "Available Packages");
$pglinks = array("", "/pkg_mgr_installed.php", "@self");
$selected_menu = "system";
require_once(__DIR__ . '/includes/head.inc');

$tab_array = array(
    array("Installed Packages", false, "/pkg_mgr_installed.php"),
    array("Available Packages", true, "/pkg_mgr.php")
);
display_top_tabs($tab_array, false, 'pills');

// Complete 69+ Package Matrix Synchronized from pfSense FreeBSD .pkg to Native Debian Linux .deb
$migrated_pkgs = array(
    array('orig' => 'acme', 'version' => '1.3.2', 'deb' => 'certbot, acme-tiny, python3-acme', 'service' => 'cron/certbot.timer', 'status' => 'Available in Debian', 'desc' => 'Automated Certificate Management Environment, for automated use of LetsEncrypt certificates. Package Dependencies: &nbsp; php85-8.5.7 &emsp; &nbsp; php85-ftp-8.5.7 &emsp; &nbsp; pecl-ssh2-1.3.1 &emsp; &nbsp; socat-1.8.1.1 &emsp;'),
    array('orig' => 'ANDwatch', 'version' => '2.1_3', 'deb' => 'arpwatch, ndpmon', 'service' => 'arpwatch.service', 'status' => 'Available in Debian', 'desc' => 'ANDwatch is a daemon for monitoring ARP and Neighbor Discovery activity, keeping track of IP to Ethernet address mappings, and providing notifications when the mappings change. Package Dependencies: &nbsp; andwatch-2.4.0 &emsp;'),
    array('orig' => 'apcupsd', 'version' => '0.3.92_12', 'deb' => 'apcupsd', 'service' => 'apcupsd.service', 'status' => 'Available in Debian', 'desc' => '"apcupsd" can be used for controlling all APC UPS models It can monitor and log the current power and battery status, perform automatic shutdown, and can run in network mode in order to power down other hosts on a LAN Package Dependencies: &nbsp; apcupsd-3.14.14_6 &emsp;'),
    array('orig' => 'arping', 'version' => '1.2.2_7', 'deb' => 'iputils-arping, arping', 'service' => 'cli', 'status' => 'Available in Debian', 'desc' => 'Broadcasts a who-has ARP packet on the network and prints answers. Package Dependencies: &nbsp; arping-2.25 &emsp;'),
    array('orig' => 'arpwatch', 'version' => '0.2.5', 'deb' => 'arpwatch', 'service' => 'arpwatch.service', 'status' => 'Available in Debian', 'desc' => 'This package contains tools that monitors ethernet activity and maintains a database of ethernet/ip address pairings. It also reports certain changes via email. Package Dependencies: &nbsp; arpwatch-3.9 &emsp;'),
    array('orig' => 'Avahi', 'version' => '2.2_10', 'deb' => 'avahi-daemon', 'service' => 'avahi-daemon.service', 'status' => 'Available in Debian', 'desc' => 'Avahi is a system which facilitates host and service discovery in local networks via mDNS (Multicast DNS) and DNS-SD (DNS Service Discovery). This package allows mDNS/DNS-SD protocols to work across multiple LAN segments. mDNS/DNS-SD is known in Apple circles as "Bonjour" and is part of the Zeroconf suite of protocols. Package Dependencies: &nbsp; avahi-app-0.8_6 &emsp; &nbsp; nss_mdns-0.14.1.20200624_1 &emsp;'),
    array('orig' => 'Backup', 'version' => '0.7', 'deb' => 'mitranet-backup, tar, rsync', 'service' => 'systemd', 'status' => 'Builtin MitraNet', 'desc' => 'Tool to Backup and Restore files and directories.'),
    array('orig' => 'bandwidthd', 'version' => '0.7.11', 'deb' => 'bandwidthd', 'service' => 'bandwidthd.service', 'status' => 'Available in Debian', 'desc' => 'BandwidthD tracks usage of TCP/IP network subnets and builds html files with graphs to display utilization. Charts are built by individual IPs, and by default display utilization over 2 day, 8 day, 40 day, and 400 day periods. Furthermore, each IP address\'s utilization can be logged out in CDF format, or to a backend database server. HTTP, TCP, UDP, ICMP, VPN, and P2P traffic are color coded. Package Dependencies: &nbsp; bandwidthd-2.0.1_12 &emsp;'),
    array('orig' => 'bind', 'version' => '9.20_8', 'deb' => 'bind9, bind9-utils', 'service' => 'named.service', 'status' => 'Available in Debian', 'desc' => 'pfSense GUI for BIND DNS server Package Dependencies: &nbsp; bind920-9.20.23 &emsp;'),
    array('orig' => 'cellular', 'version' => '1.2.8', 'deb' => 'modemmanager, libqmi-utils, libmbim-utils', 'service' => 'ModemManager.service', 'status' => 'Available in Debian', 'desc' => 'pfSense GUI for Cellular Cards Currently it supports certain Huawei models, Simcom and Quectel EC25. Package Dependencies: &nbsp; py-pyserial-3.5_4 &emsp; &nbsp; python311-3.11.15_3 &emsp;'),
    array('orig' => 'collectd', 'version' => '1.1', 'deb' => 'collectd, collectd-core', 'service' => 'collectd.service', 'status' => 'Available in Debian', 'desc' => 'collectd is a small daemon written in C for performance. It reads various system & network statistics and can forward them to another collectd server for storage. Package Dependencies: &nbsp; collectd5-5.12.0_24 &emsp;'),
    array('orig' => 'Cron', 'version' => '0.3.8_8', 'deb' => 'cron', 'service' => 'cron.service', 'status' => 'Available in Debian', 'desc' => 'The cron utility is used to manage commands on a schedule.'),
    array('orig' => 'darkstat', 'version' => '3.1.6', 'deb' => 'darkstat', 'service' => 'darkstat.service', 'status' => 'Available in Debian', 'desc' => 'darkstat is a network statistics gatherer. It\'s a packet sniffer that runs as a background process on a cable/DSL router, gathers all sorts of statistics about network usage, and serves them over HTTP. Package Dependencies: &nbsp; darkstat-3.0.721_1 &emsp;'),
    array('orig' => 'Filer', 'version' => '0.62.2', 'deb' => 'mitranet-core (REST file editor)', 'service' => 'webui', 'status' => 'Builtin MitraNet', 'desc' => 'Allows you to create and overwrite files from the GUI.'),
    array('orig' => 'freeradius3', 'version' => '0.16.4_1', 'deb' => 'freeradius, freeradius-utils', 'service' => 'freeradius.service', 'status' => 'Available in Debian', 'desc' => 'A free implementation of the RADIUS protocol. Supports MySQL, PostgreSQL, LDAP, Kerberos. Package Dependencies: &nbsp; bash-5.3.15 &emsp; &nbsp; freeradius3-3.2.10 &emsp; &nbsp; python311-3.11.15_3 &emsp;'),
    array('orig' => 'frr', 'version' => '2.1.3_3', 'deb' => 'frr, frr-pythontools', 'service' => 'frr.service', 'status' => 'Available in Debian', 'desc' => 'FRR routing daemon for BGP, OSPF, and OSPF6 Conflicts with Quagga OSPF and OpenBGPD. These packages cannot be installed at the same time. Package Dependencies: &nbsp; frr10-10.7.1 &emsp; &nbsp; frr10-pythontools-10.7.1 &emsp;'),
    array('orig' => 'FTP_Client_Proxy', 'version' => '0.3_12', 'deb' => 'frox, ftp-proxy', 'service' => 'systemd', 'status' => 'Available in Debian', 'desc' => 'Basic FTP Client Proxy using ftp-proxy from FreeBSD.'),
    array('orig' => 'haproxy', 'version' => '0.65.7', 'deb' => 'haproxy', 'service' => 'haproxy.service', 'status' => 'Available in Debian', 'desc' => 'The Reliable, High Performance TCP/HTTP(S) Load Balancer. This package implements the TCP, HTTP and HTTPS balancing features from haproxy. Supports ACLs for smart backend switching. Package Dependencies: &nbsp; haproxy-3.2.19 &emsp;'),
    array('orig' => 'haproxy-devel', 'version' => '0.66.7', 'deb' => 'haproxy', 'service' => 'haproxy.service', 'status' => 'Available in Debian', 'desc' => 'The Reliable, High Performance TCP/HTTP(S) Load Balancer. This package implements the TCP, HTTP and HTTPS balancing features from haproxy. Supports ACLs for smart backend switching. Package Dependencies: &nbsp; haproxy-devel-3.3.d10 &emsp;'),
    array('orig' => 'iperf', 'version' => '3.0.6', 'deb' => 'iperf, iperf3', 'service' => 'iperf3.service', 'status' => 'Available in Debian', 'desc' => 'Iperf is a tool for testing network throughput, loss, and jitter. Package Dependencies: &nbsp; iperf3-3.21 &emsp;'),
    array('orig' => 'LADVD', 'version' => '1.2.2_7', 'deb' => 'ladvd, lldpd', 'service' => 'ladvd.service', 'status' => 'Available in Debian', 'desc' => 'Send and decode link layer advertisements. Support for LLDP (Link Layer Discovery Protocol), CDP (Cisco Discovery Protocol), EDP (Extreme Discovery Protocol) and NDP (Nortel Discovery Protocol). Package Dependencies: &nbsp; ladvd-1.1.4 &emsp;'),
    array('orig' => 'LCDproc', 'version' => '0.12.4', 'deb' => 'lcdproc', 'service' => 'LCDd.service', 'status' => 'Available in Debian', 'desc' => 'LCD display driver. Package Dependencies: &nbsp; lcdproc-0.5.9_1 &emsp;'),
    array('orig' => 'Lightsquid', 'version' => '3.0.11', 'deb' => 'lightsquid', 'service' => 'apache2/php', 'status' => 'Available in Debian', 'desc' => 'LightSquid is a high performance web proxy reporting tool. Includes proxy realtime statistics (SQStat). Requires Squid package. Package Dependencies: &nbsp; lightsquid-1.8_5 &emsp; &nbsp; lighttpd-1.4.83 &emsp;'),
    array('orig' => 'lldpd', 'version' => '0.9.13', 'deb' => 'lldpd', 'service' => 'lldpd.service', 'status' => 'Available in Debian', 'desc' => 'lldpd provies support for the 802.1ab Link Layer Discovery Protocol (LLDP), as well as support for several proprietary discovery protocols including Cisco Discovery Protocol (CDP), Extreme Discovery Protocol (EDP), Foundry Discovery Protocol (FDP), and Nortel Discovery Protocol (NDP / SONMP). Package Dependencies: &nbsp; lldpd-1.0.21 &emsp;'),
    array('orig' => 'mailreport', 'version' => '3.6.4_7', 'deb' => 'bsd-mailx, msmtp, postfix', 'service' => 'cron', 'status' => 'Available in Debian', 'desc' => 'Allows you to setup periodic e-mail reports containing command output, and log file contents'),
    array('orig' => 'mcast-bridge', 'version' => '1.4', 'deb' => 'smcroute, pimd', 'service' => 'smcroute.service', 'status' => 'Available in Debian', 'desc' => 'Multicast Bridge is a daemon for forwarding UDP multicast data between network interfaces, supporting both IPv4 and IPv6. It supports statically configured forwarding, and dynamic interest-based forwarding using IGMP and MLD. Package Dependencies: &nbsp; mcast-bridge-1.7.0 &emsp;'),
    array('orig' => 'mDNS-Bridge', 'version' => '3.0', 'deb' => 'avahi-daemon (reflector)', 'service' => 'avahi-daemon.service', 'status' => 'Available in Debian', 'desc' => 'mDNS Bridge is a daemon for sharing Multicast DNS (mDNS) information across multiple network interfaces. This allows local DNS Service Discovery (DNS-SD) across multiple network segments, which is commonly used for sharing network print services, audio/video streaming, home automation, etc. Package Dependencies: &nbsp; mdns-bridge-3.0.0 &emsp;'),
    array('orig' => 'mtr-nox11', 'version' => '0.85.6_6', 'deb' => 'mtr-tiny', 'service' => 'cli', 'status' => 'Available in Debian', 'desc' => 'Enhanced traceroute replacement. mtr combines the functionality of the traceroute and ping programs in a single network diagnostic tool. Package Dependencies: &nbsp; mtr-0.96 &emsp;'),
    array('orig' => 'net-snmp', 'version' => '0.1.6', 'deb' => 'snmpd, snmp', 'service' => 'snmpd.service', 'status' => 'Available in Debian', 'desc' => 'A GUI for the NET-SNMP Daemon. Package Dependencies: &nbsp; net-snmp-5.9.5.2,1 &emsp;'),
    array('orig' => 'Netgate_Firmware_Upgrade', 'version' => '0.47.3', 'deb' => 'mitranet-update, apt', 'service' => 'systemd', 'status' => 'Builtin MitraNet', 'desc' => 'Provide a mechanism to update firmware of Netgate hardware Package Dependencies: &nbsp; flashrom-1.6.0_1 &emsp; &nbsp; libuuid-2.42.1 &emsp;'),
    array('orig' => 'nmap', 'version' => '1.4.4_12', 'deb' => 'nmap', 'service' => 'cli', 'status' => 'Available in Debian', 'desc' => 'Nmap is a utility for network exploration or security auditing. It supports ping scanning (determine which hosts are up), many port scanning techniques (determine what services the hosts are offering), version detection (determine what application/service is running on a port), and TCP/IP fingerprinting (remote host OS or device identification). It also offers flexible target and port specification, decoy/stealth scanning, SunRPC scanning, and more. Package Dependencies: &nbsp; nmap-7.99_1 &emsp;'),
    array('orig' => 'node_exporter', 'version' => '0.18.1_8', 'deb' => 'prometheus-node-exporter', 'service' => 'prometheus-node-exporter.service', 'status' => 'Available in Debian', 'desc' => 'Prometheus exporter for machine metrics Package Dependencies: &nbsp; node_exporter-1.11.0_3 &emsp; &nbsp; python311-3.11.15_3 &emsp;'),
    array('orig' => 'Notes', 'version' => '0.2.9_6', 'deb' => 'mitranet-core', 'service' => 'webui', 'status' => 'Builtin MitraNet', 'desc' => 'Track things you want to note for this system.'),
    array('orig' => 'nrpe', 'version' => '4.3.1_2', 'deb' => 'nagios-nrpe-server', 'service' => 'nagios-nrpe-server.service', 'status' => 'Available in Debian', 'desc' => 'pfSense software package GUI for Nagios NRPE nrpe is used to execute Nagios plugins on remote hosts and report the results to the main Nagios server. From the Nagios homepage: Allows you to execute "local" plugins (like check_disk, check_procs, etc.) on remote hosts. The check_nrpe plugin is called from Nagios and actually makes the plugin requests to the remote host. Requires that nrpe be running on the remote host (either as a standalone daemon or as a service under inetd). Package Dependencies: &nbsp; nrpe-4.1.3 &emsp;'),
    array('orig' => 'ntopng', 'version' => '6.2.0_7', 'deb' => 'ntopng, ntopng-data', 'service' => 'ntopng.service', 'status' => 'Available in Debian', 'desc' => 'ntopng (replaces ntop) is a network probe that shows network usage in a way similar to what top does for processes. In interactive mode, it displays the network status on the user\'s terminal. In Web mode it acts as a Web server, creating an HTML dump of the network status. It sports a NetFlow/sFlow emitter/collector, an HTTP-based client interface for creating ntop-centric monitoring applications, and RRD for persistently storing traffic statistics. Package Dependencies: &nbsp; gdbm-1.26 &emsp; &nbsp; graphviz-15.0.0_1 &emsp; &nbsp; libmaxminddb-1.13.3 &emsp; &nbsp; ntopng-6.6.d20260604,1 &emsp; &nbsp; redis-8.8.0 &emsp; &nbsp; webfonts-0.30_14 &emsp;'),
    array('orig' => 'nut', 'version' => '2.8.2_9', 'deb' => 'nut, nut-server, nut-client', 'service' => 'nut-server.service', 'status' => 'Available in Debian', 'desc' => 'Network UPS Tools provides support for monitoring of Uninterruptible Power Supplies. It supports UPS units attached locally via USB or serial, and remote units via the SNMP protocol, the APCUPSD protocol or the NUT protocol. Package Dependencies: &nbsp; nut-2.8.5_1 &emsp;'),
    array('orig' => 'Open-VM-Tools', 'version' => '10.1.0_8,1', 'deb' => 'open-vm-tools', 'service' => 'open-vm-tools.service', 'status' => 'Available in Debian', 'desc' => 'VMware Tools is a suite of utilities that enhances the performance of the virtual machine\'s guest operating system and improves management of the virtual machine. Package Dependencies: &nbsp; open-vm-tools-13.1.0,2 &emsp;'),
    array('orig' => 'openvpn-client-export', 'version' => '1.9.13', 'deb' => 'openvpn, easy-rsa', 'service' => 'webui', 'status' => 'Available in Debian', 'desc' => 'Exports pre-configured OpenVPN Client configurations directly from pfSense software. Package Dependencies: &nbsp; 7-zip-26.01 &emsp; &nbsp; openvpn-2.7.5 &emsp; &nbsp; openvpn-client-export-2.7.4 &emsp; &nbsp; zip-3.0_5 &emsp;'),
    array('orig' => 'pfBlockerNG', 'version' => '3.2.17_1', 'deb' => 'dnsmasq/unbound blocklists, nftables sets, ipset', 'service' => 'mitranet-firewall', 'status' => 'Builtin MitraNet', 'desc' => 'Manage IPv4/v6 List Sources into \'Deny, Permit or Match\' formats. GeoIP database by MaxMind Inc. (GeoLite2 Free version). De-Duplication, Suppression, and Reputation enhancements. Provision to download from diverse List formats. Advanced Integration for Proofpoint ET IQRisk IP Reputation Threat Sources. Domain Name (DNSBL) blocking via Unbound DNS Resolver. Package Dependencies: &nbsp; gnugrep-3.12 &emsp; &nbsp; grepcidr-2.0_1 &emsp; &nbsp; iprange-2.0.0_1 &emsp; &nbsp; jq-1.8.1 &emsp; &nbsp; libmaxminddb-1.13.3 &emsp; &nbsp; lighttpd-1.4.83 &emsp; &nbsp; php85-8.5.7 &emsp; &nbsp; php85-intl-8.5.7 &emsp; &nbsp; py-maxminddb-2.8.2 &emsp; &nbsp; py-sqlite3-3.11.15_10 &emsp; &nbsp; python311-3.11.15_3 &emsp; &nbsp; rsync-3.4.4 &emsp;'),
    array('orig' => 'pfBlockerNG-devel', 'version' => '3.2.17_1', 'deb' => 'dnsmasq/unbound blocklists, nftables sets, ipset', 'service' => 'mitranet-firewall', 'status' => 'Builtin MitraNet', 'desc' => 'pfBlockerNG-devel is the Next Generation of pfBlockerNG. Manage IPv4/v6 List Sources into \'Deny, Permit or Match\' formats. GeoIP database by MaxMind Inc. (GeoLite2 Free version). De-Duplication, Suppression, and Reputation enhancements. Provision to download from diverse List formats. Advanced Integration for Proofpoint ET IQRisk IP Reputation Threat Sources. Domain Name (DNSBL) blocking via Unbound DNS Resolver. Package Dependencies: &nbsp; gnugrep-3.12 &emsp; &nbsp; grepcidr-2.0_1 &emsp; &nbsp; iprange-2.0.0_1 &emsp; &nbsp; jq-1.8.1 &emsp; &nbsp; libmaxminddb-1.13.3 &emsp; &nbsp; lighttpd-1.4.83 &emsp; &nbsp; php85-8.5.7 &emsp; &nbsp; php85-intl-8.5.7 &emsp; &nbsp; py-maxminddb-2.8.2 &emsp; &nbsp; py-sqlite3-3.11.15_10 &emsp; &nbsp; python311-3.11.15_3 &emsp; &nbsp; rsync-3.4.4 &emsp;'),
    array('orig' => 'pimd', 'version' => '0.0.3_9', 'deb' => 'pimd', 'service' => 'pimd.service', 'status' => 'Available in Debian', 'desc' => 'PIMD Multicast Routing. Lightweight, stand-alone implementation of Protocol Independent Multicast-Sparse Mode. Conflicts with Quagga OSPF. These packages cannot be installed at the same time. Package Dependencies: &nbsp; pimd-2.3.2b_1 &emsp;'),
    array('orig' => 'RRD_Summary', 'version' => '2.2.2', 'deb' => 'rrdtool, librrds-perl', 'service' => 'webui', 'status' => 'Available in Debian', 'desc' => 'RRD Summary Page, which will give estimated month-over-month traffic passed In/Out during the specified period.'),
    array('orig' => 'Service_Watchdog', 'version' => '1.8.7_7', 'deb' => 'monit, systemd watchdog', 'service' => 'systemd', 'status' => 'Available in Debian', 'desc' => 'Monitors for stopped services and restarts them.'),
    array('orig' => 'Shellcmd', 'version' => '1.0.7', 'deb' => 'systemd, /etc/rc.local, cron @reboot', 'service' => 'systemd', 'status' => 'Builtin MitraNet', 'desc' => 'The shellcmd utility is used to manage commands on system startup.'),
    array('orig' => 'siproxd', 'version' => '1.1.8_1', 'deb' => 'siproxd', 'service' => 'siproxd.service', 'status' => 'Available in Debian', 'desc' => 'Proxy for handling NAT of multiple SIP devices to a single public IP. Package Dependencies: &nbsp; siproxd-0.8.4 &emsp;'),
    array('orig' => 'snmptt', 'version' => '1.0.3', 'deb' => 'snmptt', 'service' => 'snmptt.service', 'status' => 'Available in Debian', 'desc' => 'SNMPTT (SNMP Trap Translator) is an SNMP trap handler written in Perl for use with the Net-SNMP. Easy to setup and use. Package Dependencies: &nbsp; snmptt-1.5_1 &emsp;'),
    array('orig' => 'snort', 'version' => '4.1.10', 'deb' => 'snort, snort-rules-default', 'service' => 'snort.service', 'status' => 'Available in Debian', 'desc' => 'Snort is an open source network intrusion prevention and detection system (IDS/IPS). Combining the benefits of signature, protocol, and anomaly-based inspection. Package Dependencies: &nbsp; snort-2.9.20_9 &emsp;'),
    array('orig' => 'softflowd', 'version' => '1.2.6_4', 'deb' => 'softflowd', 'service' => 'softflowd.service', 'status' => 'Available in Debian', 'desc' => 'Softflowd is flow-based network traffic analyser capable of Cisco NetFlow data export. Softflowd semi-statefully tracks traffic flows recorded by listening on a network interface or by reading a packet capture file. These flows may be reported via NetFlow to a collecting host or summarised within softflowd itself. Softflowd supports Netflow versions 1, 5, 9 and 10 (IPFIX) and is fully IPv6-capable - it can track IPv6 flows and send export datagrams via IPv6. It also supports export to multicast groups, allowing for redundant flow collectors. Package Dependencies: &nbsp; softflowd-1.0.0_1 &emsp;'),
    array('orig' => 'squid', 'version' => '0.5.11', 'deb' => 'squid', 'service' => 'squid.service', 'status' => 'Available in Debian', 'desc' => 'High performance web proxy cache (3.5 branch). It combines Squid as a proxy server with its capabilities of acting as a HTTP / HTTPS reverse proxy. It includes an Exchange-Web-Access (OWA) Assistant, SSL filtering and antivirus integration via C-ICAP. Package Dependencies: &nbsp; c-icap-modules-0.5.7_1 &emsp; &nbsp; squid-7.4 &emsp; &nbsp; squid_radius_auth-1.10 &emsp; &nbsp; squidclamav-7.3_2 &emsp;'),
    array('orig' => 'squidGuard', 'version' => '1.16.30', 'deb' => 'squidguard', 'service' => 'squid.service', 'status' => 'Available in Debian', 'desc' => 'High performance web proxy URL filter. Package Dependencies: &nbsp; pfSense-pkg-squid-0.5.11 &emsp; &nbsp; squidguard-1.4_15 &emsp;'),
    array('orig' => 'Status_Traffic_Totals', 'version' => '2.3.5_3', 'deb' => 'vnstat, vnstati', 'service' => 'vnstat.service', 'status' => 'Available in Debian', 'desc' => 'Traffic Totals page under the Status menu, which will give a total amount of traffic passed In/Out over the period of hours, days, and months. Uses vnStat for data collection. Package Dependencies: &nbsp; vnstat-2.13 &emsp;'),
    array('orig' => 'stunnel', 'version' => '5.52.2_1', 'deb' => 'stunnel4', 'service' => 'stunnel4.service', 'status' => 'Available in Debian', 'desc' => 'SSL encryption wrapper between remote client and local or remote servers. Package Dependencies: &nbsp; stunnel-5.78,1 &emsp;'),
    array('orig' => 'sudo', 'version' => '0.3.4', 'deb' => 'sudo', 'service' => 'cli', 'status' => 'Available in Debian', 'desc' => 'sudo allows delegation of privileges to users in the shell so commands can be run as other users, such as root. Package Dependencies: &nbsp; sudo-1.9.17p2_2 &emsp;'),
    array('orig' => 'suricata', 'version' => '7.0.9_1', 'deb' => 'suricata', 'service' => 'suricata.service', 'status' => 'Available in Debian', 'desc' => 'High Performance Network IDS, IPS and Security Monitoring engine by OISF. Package Dependencies: &nbsp; suricata-8.0.5_1 &emsp;'),
    array('orig' => 'syslog-ng', 'version' => '1.16.5', 'deb' => 'syslog-ng, syslog-ng-core', 'service' => 'syslog-ng.service', 'status' => 'Available in Debian', 'desc' => 'Syslog-ng syslog server. This service is not intended to replace the default pfSense syslog server but rather acts as an independent syslog server. Package Dependencies: &nbsp; logrotate-3.22.0 &emsp; &nbsp; syslog-ng-4.11.0_2 &emsp;'),
    array('orig' => 'System_Patches', 'version' => '2.3.5_1', 'deb' => 'patch, dpkg, git', 'service' => 'cli', 'status' => 'Builtin MitraNet', 'desc' => 'A package to apply and maintain custom and recommended system patches.'),
    array('orig' => 'Tailscale', 'version' => '0.1.10', 'deb' => 'tailscale', 'service' => 'tailscaled.service', 'status' => 'Available in Debian', 'desc' => 'Tailscale is a mesh VPN alternative, based on WireGuard, that connects your computers, databases, and services together securely without any proxies. Package Dependencies: &nbsp; tailscale-1.98.5_1 &emsp;'),
    array('orig' => 'Telegraf', 'version' => '0.9.3', 'deb' => 'telegraf', 'service' => 'telegraf.service', 'status' => 'Available in Debian', 'desc' => 'Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics. Package Dependencies: &nbsp; telegraf-1.39.0 &emsp;'),
    array('orig' => 'tftpd', 'version' => '0.2', 'deb' => 'tftpd-hpa', 'service' => 'tftpd-hpa.service', 'status' => 'Available in Debian', 'desc' => 'tftpd installs and runs a TFTP server. We use the versatile tftp-hpa server. Package Dependencies: &nbsp; tftp-hpa-5.2_3 &emsp;'),
    array('orig' => 'tinc', 'version' => '1.0.39', 'deb' => 'tinc', 'service' => 'tinc.service', 'status' => 'Available in Debian', 'desc' => 'tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet. Because the tunnel appears to the IP level network code as a normal network device, there is no need to adapt any existing software. This tunnelling allows VPN sites to share information with each other over the Internet without exposing any information to others. A single tinc daemon can accept more than one connection at a time, thus making it possible to create larger virtual networks, because some limitations are circumvented. Instead of most other VPN implementations, tinc encapsulates each network packet in its own UDP packet, instead of encapsulating all into one TCP or even PPP over TCP stream. This results in lower latencies, less overhead, and in general better responsiveness and throughput. LICENSE: GPL3 or later with execption to link with OpenSSL Package Dependencies: &nbsp; tinc-1.0.37 &emsp;'),
    array('orig' => 'udpbroadcastrelay', 'version' => '1.2.8', 'deb' => 'udp-broadcast-relay-linux, bcrelay', 'service' => 'systemd', 'status' => 'Available in Debian', 'desc' => 'A GUI for UDP Broadcast Relay. This program listens for UDP broadcast packets and retransmits on additional interfaces. Package Dependencies: &nbsp; udpbroadcastrelay-1.1 &emsp;'),
    array('orig' => 'WireGuard', 'version' => '0.2.13_4', 'deb' => 'wireguard, wireguard-tools', 'service' => 'wg-quick@wg0.service', 'status' => 'ACTIVE & RUNNING (.deb)', 'desc' => 'WireGuard(R) is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN. WireGuard is designed as a general purpose VPN for running on embedded interfaces and super computers alike, fit for many different circumstances. Initially released for the Linux kernel, it is now cross-platform and widely deployable. It is currently under heavy development, but already it might be regarded as the most secure, easiest to use, and simplest VPN solution in the industry.'),
    array('orig' => 'zabbix-agent6', 'version' => '1.1_1', 'deb' => 'zabbix-agent, zabbix-agent2', 'service' => 'zabbix-agent.service', 'status' => 'Available in Debian', 'desc' => 'Zabbix agent is deployed on a monitoring target to actively monitor local resources and applications (hard drives, memory, processor statistics etc). The agent gathers operational information locally and reports data to Zabbix server for further processing. In case of failures (such as a hard disk running full or a crashed service process), Zabbix server can actively alert the administrators of the particular machine that reported the failure. Zabbix is an enterprise-class open source distributed monitoring solution. Package Dependencies: &nbsp; zabbix6-agent-6.0.46 &emsp;'),
    array('orig' => 'zabbix-agent7', 'version' => '1.1_1', 'deb' => 'zabbix-agent, zabbix-agent2', 'service' => 'zabbix-agent.service', 'status' => 'Available in Debian', 'desc' => 'Zabbix agent is deployed on a monitoring target to actively monitor local resources and applications (hard drives, memory, processor statistics etc). The agent gathers operational information locally and reports data to Zabbix server for further processing. In case of failures (such as a hard disk running full or a crashed service process), Zabbix server can actively alert the administrators of the particular machine that reported the failure. Zabbix is an enterprise-class open source distributed monitoring solution. Package Dependencies: &nbsp; zabbix7-agent-7.0.27 &emsp;'),
    array('orig' => 'zabbix-agent74', 'version' => '1.1_1', 'deb' => 'zabbix-agent, zabbix-agent2', 'service' => 'zabbix-agent.service', 'status' => 'Available in Debian', 'desc' => 'Zabbix agent is deployed on a monitoring target to actively monitor local resources and applications (hard drives, memory, processor statistics etc). The agent gathers operational information locally and reports data to Zabbix server for further processing. In case of failures (such as a hard disk running full or a crashed service process), Zabbix server can actively alert the administrators of the particular machine that reported the failure. Zabbix is an enterprise-class open source distributed monitoring solution. Package Dependencies: &nbsp; zabbix74-agent-7.4.11 &emsp;'),
    array('orig' => 'zabbix-proxy6', 'version' => '1.1_1', 'deb' => 'zabbix-proxy-sqlite3', 'service' => 'zabbix-proxy.service', 'status' => 'Available in Debian', 'desc' => 'A Zabbix proxy can collect performance and availability data on behalf of the Zabbix server. This way, a proxy can take on itself some of the load of collecting data and offload the Zabbix server. Also, using a proxy is the easiest way of implementing centralized and distributed monitoring, when all agents and proxies report to one Zabbix server and all data is collected centrally. Zabbix is an enterprise-class open source distributed monitoring solution. Package Dependencies: &nbsp; zabbix6-proxy-6.0.46 &emsp;'),
    array('orig' => 'zabbix-proxy7', 'version' => '1.1_1', 'deb' => 'zabbix-proxy-sqlite3', 'service' => 'zabbix-proxy.service', 'status' => 'Available in Debian', 'desc' => 'A Zabbix proxy can collect performance and availability data on behalf of the Zabbix server. This way, a proxy can take on itself some of the load of collecting data and offload the Zabbix server. Also, using a proxy is the easiest way of implementing centralized and distributed monitoring, when all agents and proxies report to one Zabbix server and all data is collected centrally. Zabbix is an enterprise-class open source distributed monitoring solution. Package Dependencies: &nbsp; zabbix7-proxy-7.0.27 &emsp;'),
    array('orig' => 'zabbix-proxy74', 'version' => '1.1_1', 'deb' => 'zabbix-proxy-sqlite3', 'service' => 'zabbix-proxy.service', 'status' => 'Available in Debian', 'desc' => 'A Zabbix proxy can collect performance and availability data on behalf of the Zabbix server. This way, a proxy can take on itself some of the load of collecting data and offload the Zabbix server. Also, using a proxy is the easiest way of implementing centralized and distributed monitoring, when all agents and proxies report to one Zabbix server and all data is collected centrally. Zabbix is an enterprise-class open source distributed monitoring solution. Package Dependencies: &nbsp; zabbix74-proxy-7.4.11 &emsp;'),
    array('orig' => 'zeek', 'version' => '3.0.7', 'deb' => 'zeek, zeek-core', 'service' => 'zeek.service', 'status' => 'Available in Debian', 'desc' => 'Zeek (formerly Bro) is a passive, open-source network traffic analyzer. It detects specific attacks, including those defined by signatures or events, as well as unusual activity. Package Dependencies: &nbsp; zeek-8.0.8 &emsp;'),
    array('orig' => 'xray-pfsense', 'version' => '1.8.24', 'deb' => 'xray-core (Linux amd64)', 'service' => 'xray.service', 'status' => 'ACTIVE & RUNNING (Linux amd64)', 'desc' => 'Xray-core multi-protocol proxy (VLESS Reality/Vision, VMess, Trojan, Shadowsocks, TUN)')
);
?>

<div class="panel panel-default">
	<div class="panel-heading">
		<h2 class="panel-title">Package Synchronization Status &amp; Matrix (pfSense .pkg &rarr; Debian .deb)</h2>
	</div>
	<div class="panel-body table-responsive">
		<div class="alert alert-info">
			<i class="fa-solid fa-circle-check"></i> <strong>Complete Architectural Port:</strong> 
			All <strong><?=count($migrated_pkgs)?></strong> upstream pfSense 2.9 packages have been cataloged and synchronized with native Debian 13 (Trixie) <code>.deb</code> packages, Linux systemd daemons, and in-kernel network drivers.
		</div>
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>pfSense (.pkg)</th>
					<th>Upstream Version</th>
					<th>Debian (.deb) Equivalent</th>
					<th>Systemd Service / Runtime</th>
					<th>Synchronization Status</th>
					<th>Description</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($migrated_pkgs as $p): ?>
				<tr>
					<td><strong><?=htmlspecialchars($p['orig'])?></strong></td>
					<td><span class="text-muted"><?=htmlspecialchars($p['version'])?></span></td>
					<td><code><?=htmlspecialchars($p['deb'])?></code></td>
					<td><small><?=htmlspecialchars($p['service'])?></small></td>
					<td>
						<?php if (strpos($p['status'], 'ACTIVE') !== false): ?>
							<span class="label label-success"><i class="fa-solid fa-bolt"></i> <?=htmlspecialchars($p['status'])?></span>
						<?php else: ?>
							<span class="label label-info"><i class="fa-solid fa-check"></i> <?=htmlspecialchars($p['status'])?></span>
						<?php endif; ?>
					</td>
					<td><small><?=htmlspecialchars($p['desc'])?></small></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<?php include(__DIR__ . '/includes/foot.inc'); ?>
